wandb_version: 1

client_id:
  desc: null
  value: code
output_dir:
  desc: null
  value: pretrain
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
eval_strategy:
  desc: null
  value: 'no'
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 2
per_device_eval_batch_size:
  desc: null
  value: 8
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 20
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
torch_empty_cache_steps:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.0005
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 0.3
num_train_epochs:
  desc: null
  value: 1
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: cosine
lr_scheduler_kwargs:
  desc: null
  value: {}
warmup_ratio:
  desc: null
  value: 0.03
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: pretrain/runs/May15_18-50-53_allennlp-elanding-30.reviz.ai2.in
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 1
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: epoch
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: 2
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
restore_callback_states_from_checkpoint:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
dataloader_prefetch_factor:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: pretrain-code-OLMo-2-0425-1B
disable_tqdm:
  desc: null
  value: true
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
tp_size:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: paged_adamw_32bit
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: null
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
include_for_metrics:
  desc: null
  value: []
eval_do_concat_batches:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
neftune_noise_alpha:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
batch_eval_metrics:
  desc: null
  value: false
eval_on_start:
  desc: null
  value: false
use_liger_kernel:
  desc: null
  value: false
eval_use_gather_object:
  desc: null
  value: false
average_tokens_across_devices:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.51.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747335057.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 5
      - 7
      - 13
      - 14
      - 16
      - 19
      - 23
      - 62
      4: 3.10.6
      5: 0.16.6
      6: 4.51.3
      8:
      - 5
      9:
        1: transformers_trainer
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/model_preparation_time
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
_attn_implementation_autoset:
  desc: null
  value: true
_name_or_path:
  desc: null
  value: allenai/OLMo-2-0425-1B
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - Olmo2ForCausalLM
attention_bias:
  desc: null
  value: false
attention_dropout:
  desc: null
  value: 0.0
bad_words_ids:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
cross_attention_hidden_size:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
diversity_penalty:
  desc: null
  value: 0.0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 100257
exponential_decay_length_penalty:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
hidden_act:
  desc: null
  value: silu
hidden_size:
  desc: null
  value: 2048
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 8192
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
length_penalty:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_position_embeddings:
  desc: null
  value: 4096
min_length:
  desc: null
  value: 0
model/num_parameters:
  desc: null
  value: 1484916736
model_type:
  desc: null
  value: olmo2
no_repeat_ngram_size:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 16
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_hidden_layers:
  desc: null
  value: 16
num_key_value_heads:
  desc: null
  value: 16
num_return_sequences:
  desc: null
  value: 1
output_attentions:
  desc: null
  value: false
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 100277
prefix:
  desc: null
  value: null
pretraining_tp:
  desc: null
  value: 1
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
remove_invalid_values:
  desc: null
  value: false
repetition_penalty:
  desc: null
  value: 1.0
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
rms_norm_eps:
  desc: null
  value: 1.0e-06
rope_scaling:
  desc: null
  value: null
rope_theta:
  desc: null
  value: 500000
sep_token_id:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: false
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_dtype:
  desc: null
  value: bfloat16
torchscript:
  desc: null
  value: false
transformers_version:
  desc: null
  value: 4.51.3
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 100352
